//Gonzalo Javier Bracco Varela - 233154
//Sebastian Khazzaka - 233518
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Dominio.Dueno;
import Dominio.Puesto;
import Dominio.Sistema;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Sebastian
 */
public class AltaPuesto extends javax.swing.JFrame implements PropertyChangeListener{


    public AltaPuesto() {
        initComponents();
    }
    
    public AltaPuesto(Sistema unModelo){
        modelo = unModelo;
        modelo.addPropertyChangeListener(this);
        initComponents();
        cargarLista();
        setLocationRelativeTo(null);        
    }

    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        cargarLista();
    }    
    
    public void cargarLista(){   //carga la lista de dueños
        if(modelo.getListaDueños()!=null){
        listaDueños.setListData(modelo.getListaDueños().toArray());        
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIdentificacion = new javax.swing.JTextField();
        txtUbicacion = new javax.swing.JTextField();
        spnCantEmpleados = new javax.swing.JSpinner();
        btnRegistrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaDueños = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alta Puesto");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(null);

        jLabel1.setText("Identificación");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(43, 49, 77, 17);

        jLabel2.setText("Dueño");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(43, 87, 37, 17);

        jLabel3.setText("Ubicación");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(43, 236, 58, 17);

        jLabel4.setText("Cantidad de empleados");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(43, 271, 141, 17);
        jPanel1.add(txtIdentificacion);
        txtIdentificacion.setBounds(190, 46, 210, 23);

        txtUbicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUbicacionActionPerformed(evt);
            }
        });
        jPanel1.add(txtUbicacion);
        txtUbicacion.setBounds(190, 230, 210, 23);
        jPanel1.add(spnCantEmpleados);
        spnCantEmpleados.setBounds(190, 268, 100, 23);

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar);
        btnRegistrar.setBounds(320, 320, 82, 23);

        listaDueños.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(listaDueños);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(190, 87, 210, 114);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 460, 360);

        setBounds(0, 0, 464, 388);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUbicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUbicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUbicacionActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
       try {
        String id = txtIdentificacion.getText();
        if (modelo.existePuesto(id)) {
            JOptionPane.showMessageDialog(this, "La identificación de puesto ya existe", "Error", JOptionPane.ERROR_MESSAGE);
        } 
        else {
            if (listaDueños.isSelectionEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un dueño", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            Dueno dueño = (Dueno) listaDueños.getSelectedValue();
            String ubicacion = txtUbicacion.getText();
            SpinnerNumberModel numberModel = (SpinnerNumberModel) spnCantEmpleados.getModel();
            Integer cantidadEmpleados = numberModel.getNumber().intValue();
            modelo.registrarPuesto(id, dueño, ubicacion, cantidadEmpleados);
            JOptionPane.showMessageDialog(this, "El puesto fue registrado con éxito", "Registro Éxito", JOptionPane.INFORMATION_MESSAGE);
            txtIdentificacion.setText("");
            txtUbicacion.setText("");
            spnCantEmpleados.setValue(0);
        }
       } 
       catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Ocurrió un error al registrar el puesto: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        modelo.removePropertyChangeListener(this);
    }//GEN-LAST:event_formWindowClosing
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listaDueños;
    private javax.swing.JSpinner spnCantEmpleados;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtUbicacion;
    // End of variables declaration//GEN-END:variables
    private Sistema modelo;
}
