//Gonzalo Javier Bracco Varela - 233154
//Sebastian Khazzaka - 233518
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Dominio.Dueno;
import Dominio.Sistema;
import javax.swing.JOptionPane;

/**
 *
 * @author gonzalobracco
 */
public class AltaDueno extends javax.swing.JFrame {

    /**
     * Creates new form AltaDueño
     */
    public AltaDueno() {
        initComponents();
    }
    
        public AltaDueno(Sistema unModelo) {
        modelo = unModelo;    
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        spnEdad = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        spnExperiencia = new javax.swing.JSpinner();
        btnRegistrar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alta Dueño");
        setPreferredSize(new java.awt.Dimension(300, 300));
        setSize(new java.awt.Dimension(300, 300));
        getContentPane().setLayout(null);

        jPanel1.setToolTipText("");
        jPanel1.setMinimumSize(new java.awt.Dimension(401, 268));
        jPanel1.setPreferredSize(new java.awt.Dimension(401, 268));
        jPanel1.setLayout(null);

        jLabel1.setText("Nombre");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(31, 50, 44, 16);

        jLabel2.setText("Edad");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(31, 91, 46, 16);
        jPanel1.add(txtNombre);
        txtNombre.setBounds(146, 47, 218, 22);
        jPanel1.add(spnEdad);
        spnEdad.setBounds(146, 88, 80, 22);

        jLabel3.setText("Años Experiencia");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(31, 132, 109, 16);
        jPanel1.add(spnExperiencia);
        spnExperiencia.setBounds(146, 129, 80, 22);

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar);
        btnRegistrar.setBounds(241, 206, 76, 23);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir);
        btnSalir.setBounds(146, 206, 72, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 401, 268);

        setBounds(0, 0, 460, 295);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
       try { 
        String nombre = txtNombre.getText();
        if (modelo.existeDueno(nombre)) {
            JOptionPane.showMessageDialog(this, "El dueño ya está registrado", "Error", JOptionPane.ERROR_MESSAGE);
        } 
        else {
            String edadText = spnEdad.getValue().toString();
            String experienciaText = spnExperiencia.getValue().toString();
            int edad = 0;
            int experiencia = 0;
            try {
                edad = Integer.parseInt(edadText);
                experiencia = Integer.parseInt(experienciaText);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Ingrese valores numéricos válidos en la edad y la experiencia", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            this.modelo.registrarDueño(txtNombre.getText(), edad, experiencia);
            JOptionPane.showMessageDialog(this, "El dueño fue registrado con éxito", "Registro Éxito", JOptionPane.INFORMATION_MESSAGE);
            txtNombre.setText("");  
            spnEdad.setValue(0);
            spnExperiencia.setValue(0);
        }

       } 
       catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error al registrar el dueño: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed
    
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose(); //cierra la ventana
    }//GEN-LAST:event_btnSalirActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner spnEdad;
    private javax.swing.JSpinner spnExperiencia;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
    private Sistema modelo;
}
