//Gonzalo Javier Bracco Varela - 233154
//Sebastian Khazzaka - 233518
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Dominio.Producto;
import Dominio.Sistema;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author gonzalobracco
 */
public class AltaProducto extends javax.swing.JFrame {
  
    
    /**
     * Creates new form AltaProducto
     */
    public AltaProducto() {
        initComponents();
    }
    
    public AltaProducto(Sistema unModelo) {
        modelo = unModelo;
        initComponents();
        setearSinImagen();
        String rutaArchivo = System.getProperty("user.dir") + File.separator + "ImagenesOblig" + File.separator + "Sin_Imagen.jpg"; //obtiene la imagene de la carpeta
        File archivoSeleccionado = new File(rutaArchivo); //selecciona el sin imagen como archivo al iniciar al programa
        jFileChooser1.setSelectedFile(archivoSeleccionado);
        FileNameExtensionFilter filtro = new FileNameExtensionFilter(
                "Archivos de imagen", "jpg", "jpeg", "png");
        jFileChooser1.setFileFilter(filtro);
    }   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectorArchivo = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        comboTipo = new javax.swing.JComboBox();
        comboVenta = new javax.swing.JComboBox();
        btnReset = new javax.swing.JToggleButton();
        lblImagen = new javax.swing.JLabel();
        btnAlta = new javax.swing.JButton();
        jFileChooser1 = new javax.swing.JFileChooser();
        jButtonAbrir = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        selectorArchivo.setLayout(null);

        lblNombre.setText("Nombre:");
        selectorArchivo.add(lblNombre);
        lblNombre.setBounds(53, 41, 47, 16);

        jLabel1.setText("Descripción:");
        selectorArchivo.add(jLabel1);
        jLabel1.setBounds(53, 76, 65, 16);

        jLabel2.setText("Tipo:");
        selectorArchivo.add(jLabel2);
        jLabel2.setBounds(53, 114, 26, 16);

        jLabel3.setText("Venta por:");
        selectorArchivo.add(jLabel3);
        jLabel3.setBounds(53, 155, 54, 16);

        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });
        selectorArchivo.add(txtDescripcion);
        txtDescripcion.setBounds(144, 70, 149, 22);

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        selectorArchivo.add(txtNombre);
        txtNombre.setBounds(144, 35, 149, 22);

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fruta", "Verdura" }));
        selectorArchivo.add(comboTipo);
        comboTipo.setBounds(144, 111, 149, 22);

        comboVenta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kilogramo", "Unidad" }));
        comboVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboVentaActionPerformed(evt);
            }
        });
        selectorArchivo.add(comboVenta);
        comboVenta.setBounds(144, 152, 149, 22);

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        selectorArchivo.add(btnReset);
        btnReset.setBounds(207, 249, 86, 23);

        lblImagen.setBackground(new java.awt.Color(0, 0, 0));
        lblImagen.setText("Sin imagen");
        selectorArchivo.add(lblImagen);
        lblImagen.setBounds(50, 210, 73, 70);

        btnAlta.setText("Alta");
        btnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });
        selectorArchivo.add(btnAlta);
        btnAlta.setBounds(207, 214, 86, 23);

        jFileChooser1.setControlButtonsAreShown(false);
        jFileChooser1.setCurrentDirectory(new File(System.getProperty("user.dir")+File.separator + "ImagenesOblig"));
        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });
        selectorArchivo.add(jFileChooser1);
        jFileChooser1.setBounds(311, 6, 369, 266);

        jButtonAbrir.setText("Abrir");
        jButtonAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbrirActionPerformed(evt);
            }
        });
        selectorArchivo.add(jButtonAbrir);
        jButtonAbrir.setBounds(470, 290, 72, 23);

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        selectorArchivo.add(jButtonCancelar);
        jButtonCancelar.setBounds(560, 290, 80, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(selectorArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectorArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                .addContainerGap())
        );

        setBounds(0, 0, 686, 372);
    }// </editor-fold>//GEN-END:initComponents

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed
        try {
        String nombre = txtNombre.getText();
        String descripcion = txtDescripcion.getText();
        String tipo = comboTipo.getSelectedItem().toString();
        String formaVenta = comboVenta.getSelectedItem().toString();
        String rutaArchivo = jFileChooser1.getSelectedFile().getPath();

        if (modelo.existeProducto(nombre)) {
            JOptionPane.showMessageDialog(this, "El producto ya está registrado", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            modelo.registrarProducto(nombre, descripcion, tipo, formaVenta, rutaArchivo);
            JOptionPane.showMessageDialog(this, "El Producto fue registrado con éxito", "Registro Éxitoso", JOptionPane.INFORMATION_MESSAGE);
            resetear();
        }
        } 
        catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Ocurrió un error al registrar el producto: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAltaActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        resetear();
    }//GEN-LAST:event_btnResetActionPerformed

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
      
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    private void comboVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboVentaActionPerformed

    private void jButtonAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbrirActionPerformed
       String rutaArchivo = jFileChooser1.getSelectedFile().getPath(); //aca escondimos los botones del filechooser, y le hicimos nuevos, este es "abrir"
        ImageIcon icono = new ImageIcon(rutaArchivo);
        Image imagen = icono.getImage();
        imagen = imagen.getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH);
        icono.setImage(imagen);
        lblImagen.setIcon((ImageIcon)icono); 
    }//GEN-LAST:event_jButtonAbrirActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        File archivoSeleccionado = new File("Sin_Imagen.jpg"); //y este cancelar
        jFileChooser1.setSelectedFile(archivoSeleccionado);
        resetear();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

   private void setearSinImagen(){
        String rutaArchivo = System.getProperty("user.dir");  //metodo para setear como imagen sin_imagen.jpg
        rutaArchivo += File.separator+"ImagenesOblig/Sin_Imagen.jpg";
        ImageIcon icono = new ImageIcon(rutaArchivo);
        Image imagen = icono.getImage();
        imagen = imagen.getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH);
        icono.setImage(imagen);
        lblImagen.setIcon((ImageIcon)icono);
    }
    private void resetear(){  //resetea el file que esta seleccionado en el filechooser
        txtNombre.setText("");
        txtDescripcion.setText("");
        comboTipo.setSelectedIndex(0);
        comboVenta.setSelectedIndex(0);
        File archivoSeleccionado = new File("Sin_Imagen.jpg");
        jFileChooser1.setSelectedFile(archivoSeleccionado);
        setearSinImagen();
    }
    
  


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlta;
    private javax.swing.JToggleButton btnReset;
    private javax.swing.JComboBox comboTipo;
    private javax.swing.JComboBox comboVenta;
    private javax.swing.JButton jButtonAbrir;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JPanel selectorArchivo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
    private Sistema modelo;

}
