//Gonzalo Javier Bracco Varela - 233154
//Sebastian Khazzaka - 233518
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Dominio.Mayorista;
import Dominio.Producto;
import Dominio.Sistema;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.StringJoiner;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class ConsultaMayoristas extends javax.swing.JFrame implements PropertyChangeListener{
    private Sistema modelo;
    /**
     * Creates new form ConsultaMayoristas
     */
    public ConsultaMayoristas() {
        initComponents();
    }
    
    public ConsultaMayoristas(Sistema unModelo){
        this.modelo = unModelo;
        modelo.addPropertyChangeListener(this);
        initComponents();
        actualizarTablaMayoristas();
        setTitle("Consulta de Mayoristas");
        pack();
        setLocationRelativeTo(null);
        
    }
    
    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        actualizarTablaMayoristas();
    }
    
    private void actualizarTablaMayoristas() {  
        ArrayList<Mayorista> mayoristasOrdenados = modelo.getListaMayoristas();
        
        Collections.sort(mayoristasOrdenados, Comparator.comparing(Mayorista::getNombre));//ordena los mayoristas alfabeticamente

        String[][] datosMayoristas = new String[mayoristasOrdenados.size()][4]; 

        for (int i = 0; i < mayoristasOrdenados.size(); i++) { //carga un string con los datos de los mayoristas ordenados
            Mayorista mayorista = mayoristasOrdenados.get(i);
            datosMayoristas[i][0] = mayorista.getRut();
            datosMayoristas[i][1] = mayorista.getNombre();
            datosMayoristas[i][2] = mayorista.getDireccion();
            ArrayList<Producto> listaProductosMayorista = mayorista.getListaProductos();
            Collections.sort(listaProductosMayorista, Comparator.comparing(Producto::getNombre)); //ordena los de nombres de los productos que pertenecen a ese mayorista alfabeticamente
            StringJoiner productos = new StringJoiner(", ");// Stringjoiner lo usamos aca para construir una cadena de caracteres con los nombres de los productos
            for (Producto producto : listaProductosMayorista) { 
                productos.add(producto.getNombre());
            }
            datosMayoristas[i][3] = productos.toString();
        }
        DefaultTableModel modeloTabla = (DefaultTableModel) jTableMayoristas.getModel();
        modeloTabla.setDataVector(datosMayoristas, new String[]{"RUT", "Nombre", "Dirección", "Productos"}); //toma el modelo de la tabla y lo define
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMayoristas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTableMayoristas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "RUT", "Nombre", "Dirección", "Productos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableMayoristas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        modelo.removePropertyChangeListener(this);
    }//GEN-LAST:event_formWindowClosing

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMayoristas;
    // End of variables declaration//GEN-END:variables
}
