//Gonzalo Javier Bracco Varela - 233154
//Sebastian Khazzaka - 233518
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Dominio.Producto;
import Dominio.Sistema;
import java.awt.Image;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author gonzalobracco
 */
public class ConsultaProducto extends javax.swing.JFrame implements PropertyChangeListener {

    /**
     * Creates new form ConsultaProducto
     */
    public ConsultaProducto() {
        initComponents();
    }

        public ConsultaProducto(Sistema unModelo) {
        this.modelo = unModelo;
        this.index = 0;
        modelo.addPropertyChangeListener(this);
        initComponents();
        setTitle("Consulta de Productos");
        pack();  // ajusta eltamaño del Jframe para que todos los elementos del mismo y se vean
        setLocationRelativeTo(null); // cuando abre el Jframe lo abre centrado en el medio de la pantalla
        jComboBoxTipo.setEnabled(false);
        jComboBoxVentaPor.setEnabled(false);
        recargarDatos();
    }
        
    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        recargarDatos();
    }        
    
        
    public void recargarDatos() {  //carga los datos de la interfaz de la consulta del producto
        try {
            Producto producto = modelo.listaOrdenadaProducto().get(index);
            txtNombre.setText(producto.getNombre());
            txtDescripcion.setText(producto.getDescripcion());
            if (producto.getTipo().equals("Fruta")) {
                jComboBoxTipo.setSelectedIndex(0);
            } else {
                jComboBoxTipo.setSelectedIndex(1);
            }
            if (producto.getUnidad().equals("Kilogramos")) {
                jComboBoxVentaPor.setSelectedIndex(0);
            } else {
                jComboBoxVentaPor.setSelectedIndex(1);
            }
            lblMontoTotalVendido.setText("Total $ vendido entre todos los puestos: "
                    + modelo.totalMontoVendidoPorProducto(producto));
            lblMontoTotalComprado.setText("Total $ comprado entre todos los puestos: "
                    + modelo.totalMontoCompradoPorProducto(producto));
            lblCantidadVendida.setText("Cantidad total vendida entre todos los "
                    + "puestos (unidad/kilo): " + modelo.totalCantidadVendidaPorProducto(producto));
            lblCantidadComprada.setText("Cantidad total comprada entre todos los "
                    + "puestos (unidad/kilo): " + modelo.totalCantidadCompradaPorProducto(producto));
            lblMinPrecioVenta.setText("Precio mínimo vendido: " +
                    modelo.precioMinVendidoPorProducto(producto));
            lblMaxPrecioVenta.setText("Precio máximo vendido: " +
                    modelo.precioMaxVendidoPorProducto(producto));
            jListPuestosPrecioMin.setListData(modelo.
                    listaPuestosConMenorPrecio(producto).toArray());
            jListPuestosPrecioMax.setListData(modelo.
                    listaPuestosConMayorPrecio(producto).toArray());
            String rutaArchivo = producto.getImagen();
            ImageIcon icono = new ImageIcon(rutaArchivo);
            Image imagen = icono.getImage();
            imagen = imagen.getScaledInstance(80, 80, java.awt.Image.SCALE_SMOOTH);
            icono.setImage(imagen);
            lblImagen.setIcon((ImageIcon) icono);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "La lista de productos está vacia", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblImagen = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblMontoTotalVendido = new javax.swing.JLabel();
        lblMontoTotalComprado = new javax.swing.JLabel();
        lblCantidadVendida = new javax.swing.JLabel();
        lblCantidadComprada = new javax.swing.JLabel();
        lblMinPrecioVenta = new javax.swing.JLabel();
        lblPuestosPrecioMin = new javax.swing.JLabel();
        lblMaxPrecioVenta = new javax.swing.JLabel();
        lblPuestosPrecioMax = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListPuestosPrecioMin = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListPuestosPrecioMax = new javax.swing.JList();
        jComboBoxTipo = new javax.swing.JComboBox();
        jComboBoxVentaPor = new javax.swing.JComboBox();
        txtDescripcion = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        btnSiguiente = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Nombre: ");

        jLabel2.setText("Descripción:");

        jLabel3.setText("Tipo:");

        jLabel4.setText("Venta por:");

        jLabel5.setText("Información del Producto:");

        lblMontoTotalVendido.setText("Total $ vendido entre todos los puestos:");

        lblMontoTotalComprado.setText("Total $ comprado por todos los puestos:");

        lblCantidadVendida.setText("Cantidad total vendida entre todos los puestos (unidad/kilo):");

        lblCantidadComprada.setText("Cantidad total comprada entre todos los puestos (unidad/kilo):");

        lblMinPrecioVenta.setText("Precio mínimo vendido:");

        lblPuestosPrecioMin.setText("Puestos con el precio de venta mínimo:");

        lblMaxPrecioVenta.setText("Precio máximo vendido:");

        lblPuestosPrecioMax.setText("Puestos con el precio de venta máximo:");

        jScrollPane1.setViewportView(jListPuestosPrecioMin);

        jScrollPane2.setViewportView(jListPuestosPrecioMax);

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fruta", "Verdura" }));

        jComboBoxVentaPor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kilogramo", "Unidad" }));

        txtDescripcion.setEditable(false);

        txtNombre.setEditable(false);
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        btnSiguiente.setText(">");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnAnterior.setText("<");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jComboBoxVentaPor, javax.swing.GroupLayout.Alignment.LEADING, 0, 110, Short.MAX_VALUE)
                        .addComponent(jComboBoxTipo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCantidadComprada)
                    .addComponent(lblCantidadVendida)
                    .addComponent(lblMontoTotalComprado)
                    .addComponent(lblMontoTotalVendido)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblMinPrecioVenta)
                        .addGap(131, 131, 131)
                        .addComponent(lblMaxPrecioVenta))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPuestosPrecioMin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPuestosPrecioMax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblMontoTotalVendido)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblMontoTotalComprado)
                    .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblCantidadVendida)
                    .addComponent(jComboBoxVentaPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCantidadComprada)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMinPrecioVenta)
                            .addComponent(lblMaxPrecioVenta))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPuestosPrecioMin)
                            .addComponent(lblPuestosPrecioMax))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 1027, 545);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        if(index==0){ //retrocede en la lista de productos
            index = modelo.listaOrdenadaProducto().size()-1;
        } else{
            index = index-1;
        }
        this.recargarDatos();
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        if(index==modelo.listaOrdenadaProducto().size()-1){ //avanza en la lista de productos
            index = 0;
        } else{
            index = index+1;
        }
        this.recargarDatos();
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        modelo.removePropertyChangeListener(this);  //elimina el listener al cerrar la ventana
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JComboBox jComboBoxTipo;
    private javax.swing.JComboBox jComboBoxVentaPor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList jListPuestosPrecioMax;
    private javax.swing.JList jListPuestosPrecioMin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCantidadComprada;
    private javax.swing.JLabel lblCantidadVendida;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblMaxPrecioVenta;
    private javax.swing.JLabel lblMinPrecioVenta;
    private javax.swing.JLabel lblMontoTotalComprado;
    private javax.swing.JLabel lblMontoTotalVendido;
    private javax.swing.JLabel lblPuestosPrecioMax;
    private javax.swing.JLabel lblPuestosPrecioMin;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
    private Sistema modelo;
    private int index;
}
