//Gonzalo Javier Bracco Varela - 233154
//Sebastian Khazzaka - 233518
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Dominio.Serializacion;
import Dominio.Sistema;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author gonzalobracco
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }
    
    public void iniciarSistema(){
        Sistema sistema = new Sistema();
        MenuPpal vent = new MenuPpal(sistema);
        vent.setVisible(true);
        dispose();        
    }
    
    public void iniciarSistemaProductosPrecargados(){
        //inicia el sistema segun los productos en el archivo "Productos.txt", 
        //se debera modificar el mismo si se desean productos especificos
        Sistema sistema = new Sistema();
        sistema.cargarProductosArchivo();
        MenuPpal vent = new MenuPpal(sistema);
        vent.setVisible(true);
        dispose();     
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnIniciarDeCero = new javax.swing.JButton();
        btnRetomarSistemaPrevio = new javax.swing.JButton();
        btnCargarProductos = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio");
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        btnIniciarDeCero.setText("Iniciar nuevo sistema.");
        btnIniciarDeCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarDeCeroActionPerformed(evt);
            }
        });
        jPanel1.add(btnIniciarDeCero);
        btnIniciarDeCero.setBounds(80, 70, 250, 23);

        btnRetomarSistemaPrevio.setText("Retomar desde la ultima versión.");
        btnRetomarSistemaPrevio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetomarSistemaPrevioActionPerformed(evt);
            }
        });
        jPanel1.add(btnRetomarSistemaPrevio);
        btnRetomarSistemaPrevio.setBounds(80, 170, 250, 23);

        btnCargarProductos.setText("Precargar productos a nuevo sistema.");
        btnCargarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarProductosActionPerformed(evt);
            }
        });
        jPanel1.add(btnCargarProductos);
        btnCargarProductos.setBounds(80, 120, 252, 23);

        lblTitulo.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblTitulo.setText("¡Bienvenido! Indique como desea inicializar el sistema:");
        jPanel1.add(lblTitulo);
        lblTitulo.setBounds(20, 20, 380, 18);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 410, 220);

        setBounds(0, 0, 429, 280);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRetomarSistemaPrevioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetomarSistemaPrevioActionPerformed
        try{
            Sistema sistema = Serializacion.deserealizar();
            MenuPpal vent = new MenuPpal(sistema);
            vent.setVisible(true);
        } catch (FileNotFoundException e1){
            JOptionPane.showMessageDialog(null,
                    "No se encontro archivo guardado. Iniciando"
                            + " sistema desde cero","Error",
                            JOptionPane.ERROR_MESSAGE);
            iniciarSistema();
        } catch (IOException | ClassNotFoundException e2){
            JOptionPane.showMessageDialog(null,
                    "No se encontro archivo guardado. Iniciando"
                            + " sistema desde cero", "Error",
                            JOptionPane.ERROR_MESSAGE);
            iniciarSistema();
        }
        dispose();
    }//GEN-LAST:event_btnRetomarSistemaPrevioActionPerformed

    private void btnIniciarDeCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarDeCeroActionPerformed
        iniciarSistema();
    }//GEN-LAST:event_btnIniciarDeCeroActionPerformed

    private void btnCargarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarProductosActionPerformed
        iniciarSistemaProductosPrecargados();     
    }//GEN-LAST:event_btnCargarProductosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargarProductos;
    private javax.swing.JButton btnIniciarDeCero;
    private javax.swing.JButton btnRetomarSistemaPrevio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
