//Gonzalo Javier Bracco Varela - 233154
//Sebastian Khazzaka - 233518
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Dominio.Serializacion;
import Dominio.Sistema;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author gonzalobracco
 */
public class MenuPpal extends javax.swing.JFrame {


    public MenuPpal() {
        initComponents();
    }
    
    public MenuPpal(Sistema unModelo){
        modelo = unModelo;
        initComponents();
        pack();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuRegistros = new javax.swing.JMenu();
        altaProducto = new javax.swing.JMenuItem();
        altaDueño = new javax.swing.JMenuItem();
        altaMayorista = new javax.swing.JMenuItem();
        altaPuesto = new javax.swing.JMenuItem();
        menuMovimientos = new javax.swing.JMenu();
        compra = new javax.swing.JMenuItem();
        venta = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuConsultaProducto = new javax.swing.JMenuItem();
        jMenuConsultaDuenos = new javax.swing.JMenuItem();
        jMenuConsultaPuestos = new javax.swing.JMenuItem();
        jMenuConsultaMayoristas = new javax.swing.JMenuItem();
        jMenuExportar = new javax.swing.JMenu();
        jMenuItemGenerar = new javax.swing.JMenuItem();
        menuInfo = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        menuRegistros.setText("Registros");

        altaProducto.setText("Alta Producto");
        altaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaProductoActionPerformed(evt);
            }
        });
        menuRegistros.add(altaProducto);

        altaDueño.setText("Alta Dueño");
        altaDueño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaDueñoActionPerformed(evt);
            }
        });
        menuRegistros.add(altaDueño);

        altaMayorista.setText("Alta Mayorista");
        altaMayorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaMayoristaActionPerformed(evt);
            }
        });
        menuRegistros.add(altaMayorista);

        altaPuesto.setText("Alta Puesto");
        altaPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaPuestoActionPerformed(evt);
            }
        });
        menuRegistros.add(altaPuesto);

        jMenuBar1.add(menuRegistros);

        menuMovimientos.setText("Movimientos");

        compra.setText("Compra");
        compra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compraActionPerformed(evt);
            }
        });
        menuMovimientos.add(compra);

        venta.setText("Venta");
        venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventaActionPerformed(evt);
            }
        });
        menuMovimientos.add(venta);

        jMenuBar1.add(menuMovimientos);

        jMenu1.setText("Consultas");
        jMenu1.setToolTipText("");

        jMenuConsultaProducto.setText("Productos");
        jMenuConsultaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConsultaProductoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuConsultaProducto);

        jMenuConsultaDuenos.setText("Dueños");
        jMenuConsultaDuenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConsultaDuenosActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuConsultaDuenos);

        jMenuConsultaPuestos.setText("Puestos");
        jMenuConsultaPuestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConsultaPuestosActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuConsultaPuestos);

        jMenuConsultaMayoristas.setText("Mayoristas");
        jMenuConsultaMayoristas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConsultaMayoristasActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuConsultaMayoristas);

        jMenuBar1.add(jMenu1);

        jMenuExportar.setText("Archivo");
        jMenuExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuExportarActionPerformed(evt);
            }
        });

        jMenuItemGenerar.setText("Generar");
        jMenuItemGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGenerarActionPerformed(evt);
            }
        });
        jMenuExportar.add(jMenuItemGenerar);

        jMenuBar1.add(jMenuExportar);

        menuInfo.setText("Info");
        jMenuBar1.add(menuInfo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );

        setBounds(0, 0, 509, 391);
    }// </editor-fold>//GEN-END:initComponents

    private void altaDueñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaDueñoActionPerformed
        AltaDueno vent = new AltaDueno(modelo);
        vent.setVisible(true);
    }//GEN-LAST:event_altaDueñoActionPerformed

    private void altaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaProductoActionPerformed
        AltaProducto vent = new AltaProducto(modelo);
        vent.setVisible(true);
    }//GEN-LAST:event_altaProductoActionPerformed

    private void altaMayoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaMayoristaActionPerformed
        AltaMayorista vent = new AltaMayorista(modelo);
        vent.setVisible(true);
    }//GEN-LAST:event_altaMayoristaActionPerformed

    private void altaPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaPuestoActionPerformed
        AltaPuesto vent = new AltaPuesto(modelo);
        vent.setVisible(true);
    }//GEN-LAST:event_altaPuestoActionPerformed

    private void compraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compraActionPerformed
        RegistroCompra vent = new RegistroCompra(modelo);
        vent.setVisible(true);
    }//GEN-LAST:event_compraActionPerformed

    private void ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventaActionPerformed
        RegistroVenta vent = new RegistroVenta(modelo);
        vent.setVisible(true);
    }//GEN-LAST:event_ventaActionPerformed

    private void jMenuConsultaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConsultaProductoActionPerformed
        ConsultaProducto vent = new ConsultaProducto(modelo);
        vent.setVisible(true);        
    }//GEN-LAST:event_jMenuConsultaProductoActionPerformed

    private void jMenuConsultaDuenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConsultaDuenosActionPerformed
        ConsultaDuenos vent = new ConsultaDuenos(modelo);
        vent.setVisible(true);
    }//GEN-LAST:event_jMenuConsultaDuenosActionPerformed

    private void jMenuConsultaPuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConsultaPuestosActionPerformed
        ConsultaPuestos vent = new ConsultaPuestos(modelo);
        vent.setVisible(true);
    }//GEN-LAST:event_jMenuConsultaPuestosActionPerformed

    private void jMenuConsultaMayoristasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConsultaMayoristasActionPerformed
        ConsultaMayoristas vent = new ConsultaMayoristas(modelo);
        vent.setVisible(true);
    }//GEN-LAST:event_jMenuConsultaMayoristasActionPerformed

    private void jMenuExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExportarActionPerformed

    }//GEN-LAST:event_jMenuExportarActionPerformed

    private void jMenuItemGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGenerarActionPerformed
        ExportarArchivo vent = new ExportarArchivo(modelo);
        vent.setVisible(true);
    }//GEN-LAST:event_jMenuItemGenerarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Sistema sistema = modelo;
        try {
            Serializacion.serializar(sistema);
        } catch (IOException ex) {
            Logger.getLogger(MenuPpal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem altaDueño;
    private javax.swing.JMenuItem altaMayorista;
    private javax.swing.JMenuItem altaProducto;
    private javax.swing.JMenuItem altaPuesto;
    private javax.swing.JMenuItem compra;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuConsultaDuenos;
    private javax.swing.JMenuItem jMenuConsultaMayoristas;
    private javax.swing.JMenuItem jMenuConsultaProducto;
    private javax.swing.JMenuItem jMenuConsultaPuestos;
    private javax.swing.JMenu jMenuExportar;
    private javax.swing.JMenuItem jMenuItemGenerar;
    private javax.swing.JMenu menuInfo;
    private javax.swing.JMenu menuMovimientos;
    private javax.swing.JMenu menuRegistros;
    private javax.swing.JMenuItem venta;
    // End of variables declaration//GEN-END:variables
    private Sistema modelo;
}
