//Gonzalo Javier Bracco Varela - 233154
//Sebastian Khazzaka - 233518
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Dominio.Producto;
import Dominio.Puesto;
import Dominio.Sistema;
import java.awt.*;
import java.util.ArrayList;
import javax.swing.*;
import java.awt.event.*;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;

/**
 *
 * @author Usuario
 */
public class RegistroVenta extends javax.swing.JFrame implements PropertyChangeListener {
    
    private Sistema modelo;
    
    /**
     * Creates new form RegistroVenta
     */
    public RegistroVenta() {
        initComponents();
    }
    
    public RegistroVenta(Sistema unModelo) {
        this.modelo = unModelo;
        modelo.addPropertyChangeListener(this);
        initComponents();
        panelProductos.setLayout(new GridLayout(0,2,10,10));
        cargarCombo();
        setLocationRelativeTo(null); 
    } 
    
    @Override
    public void propertyChange(PropertyChangeEvent evt) {
            Puesto puesto = (Puesto)jComboBoxPuesto.getSelectedItem();
            if(puesto!=null){
                cargarCombo();
                actualizarGrilla(puesto);
            }    
    }      
    
    public void cargarCombo(){ // carga el combo con los puestos a seleccionar
            DefaultComboBoxModel<Puesto> comboBoxModel = new DefaultComboBoxModel<>();
            ArrayList <Puesto> listaPuestos = modelo.getListaPuestos();
            for (Puesto puesto : listaPuestos) {
                comboBoxModel.addElement(puesto);
            }
            jComboBoxPuesto.setModel(comboBoxModel);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPuesto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxPuesto = new javax.swing.JComboBox();
        panelScroll = new javax.swing.JScrollPane();
        panelProductos = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Puestos:");

        jComboBoxPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPuestoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPuestoLayout = new javax.swing.GroupLayout(jPanelPuesto);
        jPanelPuesto.setLayout(jPanelPuestoLayout);
        jPanelPuestoLayout.setHorizontalGroup(
            jPanelPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPuestoLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanelPuestoLayout.setVerticalGroup(
            jPanelPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPuestoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanelPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelProductosLayout = new javax.swing.GroupLayout(panelProductos);
        panelProductos.setLayout(panelProductosLayout);
        panelProductosLayout.setHorizontalGroup(
            panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
        );
        panelProductosLayout.setVerticalGroup(
            panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 378, Short.MAX_VALUE)
        );

        panelScroll.setViewportView(panelProductos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelScroll)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPuesto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelScroll)
                .addContainerGap())
        );

        setBounds(0, 0, 732, 420);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPuestoActionPerformed
        Puesto puesto = (Puesto)jComboBoxPuesto.getSelectedItem();
        actualizarGrilla(puesto);
    }//GEN-LAST:event_jComboBoxPuestoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        modelo.removePropertyChangeListener(this);
    }//GEN-LAST:event_formWindowClosing
    
    private void actualizarGrilla(Puesto unPuesto) throws NullPointerException {
        panelProductos.removeAll();
        ArrayList<Producto> lista = modelo.listaOrdenadaProductosDisponiblePorPuesto(unPuesto);
        for (Producto producto : lista) {
            JButton btnProducto = new JButton();
            btnProducto.setToolTipText(producto.getNombre());
            ImageIcon icono = new ImageIcon(producto.getImagen());
            btnProducto.setIcon(new ImageIcon(icono.getImage().
                    getScaledInstance(60, 60, java.awt.Image.SCALE_SMOOTH)));
            btnProducto.putClientProperty(producto.getNombre(), producto);
            btnProducto.addActionListener(new ProcesoProducto());
            panelProductos.add(btnProducto);
        }
        panelProductos.revalidate();
        panelProductos.repaint();
    }
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBoxPuesto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelPuesto;
    private javax.swing.JPanel panelProductos;
    private javax.swing.JScrollPane panelScroll;
    // End of variables declaration//GEN-END:variables


    private class ProcesoProducto implements ActionListener {
        public void actionPerformed(ActionEvent e) {
            JButton cual = ((JButton) e.getSource());     
            Producto producto = (Producto)cual.getClientProperty(cual.getToolTipText());
            crearVentanaEmergente(producto,cual);
        }


        public void crearVentanaEmergente(Producto producto, JButton boton){
            JPanel panel = new JPanel(new GridLayout(0,1));
            JLabel lblPrecio = new JLabel ("Precio: ");
            JTextField txtPrecio = new JTextField();
            JLabel lblCantidad = new JLabel ("Cantidad: ");
            JTextField txtCantidad = new JTextField();
            JButton btnAceptar = new JButton("Aceptar");
            btnAceptar.addActionListener(new ActionListener(){
                public void actionPerformed(ActionEvent e) {
                    int cantidad = Integer.parseInt(txtCantidad.getText());
                    int precio = Integer.parseInt(txtPrecio.getText());
                    if (cantidad <= producto.getStock()) {
                        modelo.registrarVenta((Puesto)jComboBoxPuesto.getSelectedItem(),
                                producto, cantidad, precio);
                        JOptionPane.showMessageDialog(boton.getParent(),
                                "Venta realizada con éxito",
                                "Venta", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(boton.getParent(),
                                "La cantidad supera el stock disponible.\n"+"El stock"
                                        + " disponible es de: "+producto.getStock(),
                                "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            });
            panel.add(lblPrecio);
            panel.add(txtPrecio);
            panel.add(lblCantidad);
            panel.add(txtCantidad);
            panel.add(btnAceptar);
            JOptionPane.showOptionDialog(boton.getParent(), 
                    panel, 
                    producto.getNombre(), 
                    JOptionPane.DEFAULT_OPTION,
                    JOptionPane.PLAIN_MESSAGE,
                    null,
                    new Object[]{},
                    null);
        }


    }

}

    
